#!/usr/bin/env python3
"""
generate_post.py — autonomous blog post generator for kadal
reads recent conversations → asks Claude Sonnet → saves as Jupyter notebook
→ converts to markdown → Hugo build → git push

runs 3x daily via launchd (8am, 2pm, 8pm)
"""

import json
import os
import sys
import subprocess
import logging
from datetime import datetime, timezone, timedelta
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(os.path.expanduser("~/.env"))

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

# === PATHS ===
KADAL_DIR       = Path.home() / "kadal"
POSTS_DIR       = KADAL_DIR / "content" / "posts"
NOTEBOOKS_DIR   = KADAL_DIR / "notebooks"
CONVERSATIONS   = Path.home() / "training" / "conversations" / "conversations.jsonl"

# === CONFIG ===
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
LOOKBACK_HOURS    = 8
MODEL             = "claude-sonnet-4-6"

SYSTEM_PROMPT = """you are kadal, a deeply analytical ai assistant. you think rigorously, show your reasoning process, analyze patterns, and occasionally share sharp opinions. you write in lowercase. you are writing a technical blog post based on recent conversations and observations.

be specific, go deep, show your work. format your response as a jupyter notebook json with:
- markdown cells for analysis, observations, and opinions
- code cells for any data visualization or computation (use matplotlib/seaborn/pandas)
- a clear title (lowercase) in the first markdown cell as a # heading
- tags and categories at the end as html comments: <!-- tags: tag1, tag2 --> <!-- categories: cat1 -->

start with the most interesting insight from the conversations. don't summarize — analyze."""

def load_recent_conversations(hours: int = 8) -> list[dict]:
    if not CONVERSATIONS.exists():
        log.warning(f"No conversations file at {CONVERSATIONS}")
        return []

    cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)
    recent = []
    with open(CONVERSATIONS, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
                ts = datetime.fromisoformat(entry["timestamp"])
                if ts >= cutoff:
                    recent.append(entry)
            except Exception:
                continue
    return recent

def conversations_to_text(conversations: list[dict]) -> str:
    lines = []
    for c in conversations:
        for msg in c.get("messages", []):
            role = msg.get("role", "?")
            content = msg.get("content", "").strip()
            lines.append(f"[{role}]: {content}")
        lines.append("")
    return "\n".join(lines)

def generate_notebook_via_claude(conversation_text: str) -> dict:
    import anthropic
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    user_message = f"""here are the recent conversations from the last {LOOKBACK_HOURS} hours:

---
{conversation_text}
---

write a technical blog post as a jupyter notebook json object. do NOT wrap in markdown code fences. return ONLY the raw json, one line per cell source array (escape newlines as \\n in json strings)."""

    log.info(f"Calling Claude {MODEL}...")
    message = client.messages.create(
        model=MODEL,
        max_tokens=4096,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_message}]
    )

    raw = message.content[0].text.strip()

    # strip markdown code fences if present
    if raw.startswith("```"):
        lines = raw.split("\n")
        raw = "\n".join(lines[1:-1] if lines[-1] == "```" else lines[1:])

    try:
        return json.loads(raw)
    except json.JSONDecodeError as e:
        log.error(f"JSON parse failed: {e}")
        raise

def make_fallback_notebook(title: str, conversation_text: str) -> dict:
    """Simple fallback notebook when Claude is unavailable."""
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"}
        },
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [f"# {title}\n\n*generated by kadal*\n\n<!-- tags: observations, log -->\n<!-- categories: daily -->"]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## recent activity\n\nconversation snapshot from the last 8 hours:\n\n```\n" + conversation_text[:2000] + "\n```"]
            }
        ]
    }

def extract_tags_categories(notebook: dict) -> tuple[list, list]:
    """Pull tags/categories from HTML comments in markdown cells."""
    import re
    tags, cats = ["observations"], ["daily"]
    for cell in notebook.get("cells", []):
        if cell.get("cell_type") == "markdown":
            src = "".join(cell.get("source", []))
            t = re.search(r"<!-- tags: ([^>]+) -->", src)
            c = re.search(r"<!-- categories: ([^>]+) -->", src)
            if t:
                tags = [x.strip() for x in t.group(1).split(",")]
            if c:
                cats = [x.strip() for x in c.group(1).split(",")]
    return tags, cats

def extract_title(notebook: dict) -> str:
    """Pull title from first markdown cell h1."""
    import re
    for cell in notebook.get("cells", []):
        if cell.get("cell_type") == "markdown":
            src = "".join(cell.get("source", []))
            m = re.search(r"^#\s+(.+)$", src, re.MULTILINE)
            if m:
                return m.group(1).strip().lower()
    return "untitled"

def save_notebook(notebook: dict, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(notebook, f, indent=2)
    log.info(f"Notebook saved: {path}")

def convert_to_markdown(nb_path: Path, output_dir: Path) -> Path:
    """Convert Jupyter notebook to markdown by extracting markdown cells."""
    output_dir.mkdir(parents=True, exist_ok=True)
    md_path = output_dir / (nb_path.stem + ".md")
    
    # Read notebook and extract markdown
    with open(nb_path, "r") as f:
        nb = json.load(f)
    
    lines = []
    for cell in nb.get("cells", []):
        if cell.get("cell_type") == "markdown":
            src = cell.get("source", [])
            if isinstance(src, list):
                lines.extend(src)
            else:
                lines.append(src)
            lines.append("\n")
        elif cell.get("cell_type") == "code":
            lines.append("\n```python\n")
            src = cell.get("source", [])
            if isinstance(src, list):
                lines.extend(src)
            else:
                lines.append(src)
            lines.append("\n```\n")
    
    md_path.write_text("".join(lines))
    log.info(f"Markdown generated: {md_path}")
    return md_path

def add_hugo_frontmatter(md_path: Path, title: str, tags: list, cats: list, slug: str):
    """Prepend Hugo front matter to the converted markdown."""
    now = datetime.now(timezone.utc)
    frontmatter = f"""---
title: "{title}"
date: {now.strftime('%Y-%m-%dT%H:%M:%S+00:00')}
draft: false
tags: [{', '.join(f'"{t}"' for t in tags)}]
categories: [{', '.join(f'"{c}"' for c in cats)}]
showToc: false
---

"""
    content = md_path.read_text()
    # strip the h1 (already in frontmatter as title)
    import re
    content = re.sub(r"^#\s+.+\n", "", content, count=1)
    # strip tag/category comments
    content = re.sub(r"<!-- (tags|categories): [^>]+ -->\n?", "", content)
    md_path.write_text(frontmatter + content)

def hugo_build():
    result = subprocess.run(
        ["hugo", "--minify"],
        cwd=str(KADAL_DIR),
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f"hugo build failed:\n{result.stderr}")
    log.info("Hugo build successful.")

def git_push(slug: str):
    cmds = [
        ["git", "add", "-A"],
        ["git", "commit", "-m", f"post: {slug}"],
        ["git", "push", "origin", "main"],
    ]
    for cmd in cmds:
        result = subprocess.run(cmd, cwd=str(KADAL_DIR), capture_output=True, text=True)
        if result.returncode != 0:
            # empty commit is fine
            if "nothing to commit" in result.stdout + result.stderr:
                log.info("Nothing new to commit.")
                return
            raise RuntimeError(f"{' '.join(cmd)} failed:\n{result.stderr}")
    log.info("Pushed to GitHub.")

def main():
    if not ANTHROPIC_API_KEY:
        log.error("ANTHROPIC_API_KEY not set in ~/.env")
        sys.exit(1)

    now = datetime.now(timezone.utc)
    slug = now.strftime("%Y-%m-%d-%H%M")
    nb_path = NOTEBOOKS_DIR / f"{slug}.ipynb"
    md_final = POSTS_DIR / f"{slug}.md"

    log.info(f"=== kadal post generation: {slug} ===")

    # Load recent conversations
    convos = load_recent_conversations(LOOKBACK_HOURS)
    log.info(f"Loaded {len(convos)} conversations from last {LOOKBACK_HOURS}h")

    if not convos:
        log.warning("No recent conversations — generating reflective post anyway.")
        conversation_text = "no conversations in the last 8 hours. this is a reflective post."
    else:
        conversation_text = conversations_to_text(convos)

    # Generate notebook via Claude
    try:
        notebook = generate_notebook_via_claude(conversation_text)
    except Exception as e:
        log.warning(f"Claude call failed ({e}), using fallback notebook.")
        notebook = make_fallback_notebook(slug, conversation_text)

    # Extract metadata
    title  = extract_title(notebook)
    tags, cats = extract_tags_categories(notebook)

    # Save notebook
    save_notebook(notebook, nb_path)

    # Convert to markdown
    tmp_md = convert_to_markdown(nb_path, POSTS_DIR)

    # Rename to final slug-based name and add frontmatter
    tmp_md.rename(md_final) if tmp_md != md_final else None
    add_hugo_frontmatter(md_final, title, tags, cats, slug)
    log.info(f"Post ready: {md_final}")

    # Hugo build
    hugo_build()

    # Git push
    git_push(slug)

    log.info(f"✅ Done. Post '{title}' live at https://nakiara.github.io/kadal/")

if __name__ == "__main__":
    main()
